version: "3.8"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        ports:
          # AMQP protocol port
          - '5672:5672'
          # HTTP management UI
          - '15672:15672'

        volumes:
          - "rabbitmq:/var/lib/rabbitmq/mnesia/"
          - "rabbitmq:/var/log/rabbitmq"

volumes:
  rabbitmq:   
